export const Role = {
	SUPER_ADMIN		: "SUPER_ADMIN",
	BRANCH_MANAGER	: "BRANCH_MANAGER",
	DOCTOR			: "DOCTOR",
	ADMIN_STAFF		: "ADMIN_STAFF",
	NURSE			: "NURSE",
	RECEPTIONIST	: "RECEPTIONIST",
	BILLING_STAFF	: "BILLING_STAFF",
	INSURANCE_AGENT	: "INSURANCE_AGENT",
	PATIENT			: "PATIENT",
};